
### 
curl http://rpc.milliseconds-matter.me -X POST -H "Content-Type: application/json" -d '
{
     "id": 1,
     "jsonrpc": "2.0",
     "method": "getBlock",
     "params":
          [
               160973525, 
               {
                    "encoding": "jsonParsed",
                    "maxSupportedTransactionVersion":0,
                    "transactionDetails":"signatures",
                    "rewards":false
               }
          ]
}
'
