### SP anycast IP address

curl http://151.139.128.10:8080 -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": "null",
    "method": "getTransactionCount"
  }
'
### anycast address for ec workload
curl http://69.197.3.4:8080 -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": "null",
    "method": "getTransactionCount"
  }
'

###
curl https://arion.earth/rpc -X POST -H "Content-Type: application/json" -d ' 
  {
    "jsonrpc": "2.0",
    "id": "null",
    "method": "getLatestBlockhash"
  }
'
### cdn site address: sea 
curl https://y4i3j6c3.stackpathcdn.com -X POST -H "Content-Type: application/json" -d ' 
  {
    "jsonrpc": "2.0",
    "id": "null",
    "method": "getLatestBlockhash"
  }
'
### cdn site address: mia 
curl d7b5c9i5.stackpathcdn.com -X POST -H "Content-Type: application/json" -d ' 
  {
    "jsonrpc": "2.0",
    "id": "null",
    "method": "getLatestBlockhash"
  }
'
### cdn site address: fra 
curl c6k4s4a4.stackpathcdn.com -X POST -H "Content-Type: application/json" -d ' 
  {
    "jsonrpc": "2.0",
    "id": "null",
    "method": "getLatestBlockhash"
  }
'
### cdn site address: sin 
curl y4i3j6c3.stackpathcdn.com -X POST -H "Content-Type: application/json" -d ' 
  {
    "jsonrpc": "2.0",
    "id": "null",
    "method": "getLatestBlockhash"
  }
'